server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newstart?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 123456
  profiles:
    include: mysql


mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml,classpath*:/mapper/*.xml
